[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
genome_contract = "3wPJRuHnSkRK3hjhbRSevr2ERzXvEXZWFeoh66RYqp4v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/genome.ts"
