[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
genome_solana = "572G4eB1NNusfqGj3DVTZw1ZooweLBiaA3ko7fLhSsV2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/admin.json"

[scripts]
test-omni = "sh scripts/run_required_tests_omni.sh && pkill -9 solana-test-validator"
test-omni-all = "sh scripts/run_tests_omni.sh && pkill -9 solana-test-validator"
test-single-cancel = "sh scripts/run_cancel_tests_single.sh && pkill -9 solana-test-validator"
test-single-cancel-all = "sh scripts/run_cancel_tests_single_all.sh && pkill -9 solana-test-validator"
test-single-finish = "sh scripts/run_finish_tests_single.sh && pkill -9 solana-test-validator"
test-single-finish-all = "sh scripts/run_finish_tests_single_all.sh && pkill -9 solana-test-validator"
test-single-all = "sh scripts/run_tests_single.sh && pkill -9 solana-test-validator"
test-all = "anchor run test-ci && pkill -9 solana-test-validator"
test-ci = "sh scripts/run_tests.sh"
initialize-omni = "yarn run ts-node migrations/omnichain/initializeOmnichain.ts keys/deployer.json"
set-bridge-fee = "yarn run ts-node migrations/omnichain/setBridgeFee.ts keys/admin.json"
initialize-single = "yarn run ts-node migrations/singlechain/initializeSinglechain.ts keys/deployer.json 6MurAyX9MiuLV8ufEeAN26w1KTbT1yDKCAcQF1bHQHCx"
create-ata = "yarn run ts-node migrations/singlechain/createAta.ts"
grant-role = "yarn run ts-node migrations/singlechain/grantRole.ts keys/admin.json"
revoke-role = "yarn run ts-node migrations/singlechain/revokeRole.ts keys/admin.json"
approve-token = "yarn run ts-node migrations/singlechain/approveToken.ts"
ban-token = "yarn run ts-node migrations/singlechain/banToken.ts"
create-tournament = "yarn run ts-node migrations/singlechain/createTournament.ts"
register-tournament = "yarn run ts-node migrations/singlechain/registerTournament.ts"
start-tournament = "yarn run ts-node migrations/singlechain/startTournament.ts"
cancel-tournament = "yarn run ts-node migrations/singlechain/cancelTournament.ts"
finish-tournament = "yarn run ts-node migrations/singlechain/finishTournament.ts"
claim-refund = "yarn run ts-node migrations/singlechain/claimRefund.ts"
claim-role-fund = "yarn run ts-node migrations/singlechain/claimRoleFund.ts"
claim-sponsor-refund = "yarn run ts-node migrations/singlechain/claimSponsorRefund.ts"
claim-reward = "yarn run ts-node migrations/singlechain/claimReward.ts"
set-bloom-precision = "yarn run ts-node migrations/singlechain/setBloomPrecision.ts keys/admin.json"
