[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
genome_contract = "E8Pa2NFPqUCqZ9PUweRxyMzHcHphyGWwzx7VhDc5dPyv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/genome.ts"
initialize = "yarn run ts-node migrations/initialize.ts"
setup-genome = "yarn run ts-node migrations/setup_genome.ts"
grant-role = "yarn run ts-node migrations/grant_role.ts"
revoke-role = "yarn run ts-node migrations/revoke_role.ts"
